{% set version = '0.4.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dirichletprocess
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dirichletprocess_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dirichletprocess/dirichletprocess_{{ version }}.tar.gz
  sha256: cade35f31185c257414f960d48a5cff4048f31e3fa9468afdd9f15dcad5757bf

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
    - r-gtools
    - r-mvtnorm
  run:
    - r-base
    - r-ggplot2
    - r-gtools
    - r-mvtnorm

test:
  commands:
    - $R -e "library('dirichletprocess')"           # [not win]
    - "\"%R%\" -e \"library('dirichletprocess')\""  # [win]

about:
  home: https://github.com/dm13450/dirichletprocess
  license: GPL-3.0-or-later
  summary: 'Perform nonparametric Bayesian analysis using Dirichlet processes without the need
    to program the inference algorithms. Utilise included pre-built models or specify
    custom models and allow the ''dirichletprocess'' package to handle the Markov chain
    Monte Carlo sampling. Our Dirichlet process objects can act as building blocks for
    a variety of statistical models including and not limited to: density estimation,
    clustering and prior distributions in hierarchical models. See Teh, Y. W. (2011)
    <https://www.stats.ox.ac.uk/~teh/research/npbayes/Teh2010a.pdf>, among many other
    sources.'
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - dillonroach

# Package: dirichletprocess
# Type: Package
# Title: Build Dirichlet Process Objects for Bayesian Modelling
# Version: 0.4.0
# Authors@R: c( person("Gordon", "J. Ross", email="gordon@gordonjross.co.uk", role=c("aut")), person("Dean", "Markwick", email="dean.markwick@talk21.com", role=c("aut", "cre")), person("Kees", "Mulder", email="keestimmulder@gmail.com", role=c("ctb"), comment = c(ORCID = "0000-0002-5387-3812")), person("Giovanni", "Sighinolfi", email ="giovanni.sighinolfi2@studio.unibo.it", role=c("ctb")) )
# Maintainer: Dean Markwick <dean.markwick@talk21.com>
# Description: Perform nonparametric Bayesian analysis using Dirichlet processes without the need to program the inference algorithms. Utilise included pre-built models or specify custom models and allow the 'dirichletprocess' package to handle the Markov chain Monte Carlo sampling. Our Dirichlet process objects can act as building blocks for a variety of statistical models including and not limited to: density estimation, clustering and prior distributions in hierarchical models. See Teh, Y. W. (2011) <https://www.stats.ox.ac.uk/~teh/research/npbayes/Teh2010a.pdf>, among many other sources.
# Depends: R (>= 2.10)
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# Suggests: testthat, knitr, rmarkdown, tidyr, dplyr
# Imports: gtools, ggplot2, mvtnorm
# URL: https://github.com/dm13450/dirichletprocess
# BugReports: https://github.com/dm13450/dirichletprocess/issues
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2020-06-13 10:22:08 UTC; deanmarkwick
# Author: Gordon J. Ross [aut], Dean Markwick [aut, cre], Kees Mulder [ctb] (<https://orcid.org/0000-0002-5387-3812>), Giovanni Sighinolfi [ctb]
# Repository: CRAN
# Date/Publication: 2020-06-13 10:40:02 UTC
